#!/usr/bin/with-contenv sh
set -e


	if [ -z "$WORDPRESS_DB_HOST" ]; then
		echo >&2 'error: missing WORDPRESS_DB_HOST and MYSQL_PORT_3306_TCP environment variables'
		echo >&2 '  Did you forget to --link some_mysql_container:mysql or set an external db'
		echo >&2 '  with -e WORDPRESS_DB_HOST=hostname:port?'
		exec s6-svscanctl -t /var/run/s6/services
	fi

	if [ -z "$WORDPRESS_DB_USER" ]; then
		WORDPRESS_DB_USER=root
	fi
	if [ -z "$WORDPRESS_DB_USER" ]; then
		WORDPRESS_DB_NAME=wordpress
	fi

	if [ -z "$WORDPRESS_DB_PASSWORD" ]; then
		echo >&2 'error: missing required WORDPRESS_DB_PASSWORD environment variable'
		echo >&2 '  Did you forget to -e WORDPRESS_DB_PASSWORD=... ?'
		echo >&2
		echo >&2 '  (Also of interest might be WORDPRESS_DB_USER and WORDPRESS_DB_NAME.)'
		exec s6-svscanctl -t /var/run/s6/services
	fi

	if ! [ -e index.php -a -e wp-includes/version.php ]; then
		echo >&2 "WordPress not found in $(pwd) - copying now..."
		if [ "$(ls -A)" ]; then
			echo >&2 "WARNING: $(pwd) is not empty - press Ctrl+C now if this is an error!"
			( set -x; ls -A; sleep 10 )
		fi
		tar cf - -C /usr/src/wordpress . | tar xf -
		echo >&2 "Complete! WordPress has been successfully copied to $(pwd)"
	fi



	if [ ! -e wp-config.php ]; then
		awk '/^\/\*.*stop editing.*\*\/$/ && c == 0 { c = 1; system("cat") } { print }' wp-config-sample.php > wp-config.php <<'EOPHP'
// If we're behind a proxy server and using HTTPS, we need to alert Wordpress of that fact
// see also http://codex.wordpress.org/Administration_Over_SSL#Using_a_Reverse_Proxy
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
	$_SERVER['HTTPS'] = 'on';
}

EOPHP
		chown www-data:www-data wp-config.php
	fi



  sed -i "/DB_HOST/s/'[^']*'/'$WORDPRESS_DB_HOST'/2" wp-config.php
  sed -i "/DB_NAME/s/'[^']*'/'$WORDPRESS_DB_NAME'/2" wp-config.php
  sed -i "/DB_USER/s/'[^']*'/'$WORDPRESS_DB_USER'/2" wp-config.php
  sed -i "/DB_PASSWORD/s/'[^']*'/'$WORDPRESS_DB_PASSWORD'/2" wp-config.php


	for unique in AUTH_KEY SECURE_AUTH_KEY LOGGED_IN_KEY NONCE_KEY AUTH_SALT SECURE_AUTH_SALT LOGGED_IN_SALT NONCE_SALT; do
		eval unique_value=\$WORDPRESS_$unique
		if [ "$unique_value" ]; then
			  sed -i "/$unique/s/'[^']*'/'$unique_value'/2" wp-config.php

		else
				sed -i "/$unique/s/'[^']*'/'$(head -c 1m /dev/urandom | sha1sum | cut -d' ' -f1)'/2" wp-config.php
		fi
	done


	if [ "$WORDPRESS_TABLE_PREFIX" ]; then
		sed -i "s/'wp_'/'$WORDPRESS_TABLE_PREFIX'/" wp-config.php
	fi

	if [ "$WORDPRESS_DEBUG" ]; then
		sed -i "/WP_DEBUG/s/'[^']*'/true/2" wp-config.php
	fi

	TERM=dumb php -- "$WORDPRESS_DB_HOST" "$WORDPRESS_DB_USER" "$WORDPRESS_DB_PASSWORD" "$WORDPRESS_DB_NAME" <<'EOPHP'
<?php
// database might not exist, so let's try creating it (just to be safe)

$stderr = fopen('php://stderr', 'w');

list($host, $port) = explode(':', $argv[1], 2);

$maxTries = 10;
do {
	$mysql = new mysqli($host, $argv[2], $argv[3], '', (int)$port);
	if ($mysql->connect_error) {
		fwrite($stderr, "\n" . 'MySQL Connection Error: (' . $mysql->connect_errno . ') ' . $mysql->connect_error . "\n");
		--$maxTries;
		if ($maxTries <= 0) {
			exit(1);
		}
		sleep(3);
	}
} while ($mysql->connect_error);

if (!$mysql->query('CREATE DATABASE IF NOT EXISTS `' . $mysql->real_escape_string($argv[4]) . '`')) {
	fwrite($stderr, "\n" . 'MySQL "CREATE DATABASE" Error: ' . $mysql->error . "\n");
	$mysql->close();
	exit(1);
}

$mysql->close();
EOPHP
